### ISSUE TITLE
Is it possible to use groq API

### ISSUE THREAD

**Issue by aborruso** [quackscience/duckdb-extension-openprompt#10]
Hi,
groq should be OpenAI compliant: https://console.groq.com/docs/openai

If I try to set it, I have 404 error

Thank you

![image](https://github.com/user-attachments/assets/3d5a9daf-8b0c-4d01-a98f-105c7f6ab088)

**Comment by lmangani** [comment]
You need to try provide the full completions API path, ie: `https://api.groq.com/openai/v1/chat/completions`
Why? this extension currently only supports this API and for this reason requires an explicit URL pointing at it.

**Comment by lmangani** [comment]
API path confirmed by the groq docs: https://console.groq.com/docs/api-reference#chat

**Comment by aborruso** [comment]
Grazie @lmangani these my steps

```
D SET VARIABLE openprompt_api_url = 'https://api.groq.com/openai/v1/chat/completions';
D SET VARIABLE openprompt_model_name = 'groq-llama3-70b';
D LOAD open_prompt;
D SET VARIABLE openprompt_api_token = 'gsk_CIhrphxxxxxxxxxxxxxxxxxxxxxxxxxxjBXPEIRHuz';
D SELECT open_prompt('Write a one-line poem about ducks') AS response;
```

And I get

```
┌──────────────────────────────────┐
│             response             │
│             varchar              │
├──────────────────────────────────┤
│ Error: HTTP error 404: Not Found │
└──────────────────────────────────┘
```

Thank you

**Comment by lmangani** [comment]
The groq documentation states the API exists. Perhaps other groq users can assist here... if you find the reason let us know

**Comment by aborruso** [comment]
Hi @lmangani if I run a RAW call to the API

```
curl https://api.groq.com/openai/v1/chat/completions \
  -H "Authorization: Bearer $GROQ_API_KEY" \
  -H "Content-Type: application/json" \
  -d '{
    "model": "mixtral-8x7b-32768",
    "messages": [
      {
        "role": "user",
        "content": "Ciao! Come stai?"
      }
    ],
    "temperature": 0.7,
    "max_tokens": 1024
  }'
```

I have a reply

```
{"id":"chatcmpl-2560ba1b-3a69-43f3-a882-1c85d9d09700","object":"chat.completion","created":1730046840,"model":"mixtral-8x7b-32768","choices":[{"index":0,"message":{"role":"assistant","content":"Hello! I'm just a computer program, so I don't have feelings, but I'm here and ready to help you with any language-related questions you have. Is there something specific you'd like to know or practice today?\n\nIf you're a language learner, it can be helpful to practice short, focused conversations to build your skills. Here are a few questions you could ask me to get started:\n\n* How do you say [word or phrase] in [language]?\n* Can you give me an example sentence using [word or phrase] in [language]?\n* How would you translate this sentence from English to [language]: [sentence]?\n* Can you explain the difference between [word or phrase] and [word or phrase] in [language]?\n* Can you help me practice pronouncing [word or phrase] in [language]?\n\nI'm looking forward to chatting with you!"},"logprobs":null,"finish_reason":"stop"}],"usage":{"queue_time":0.012524184,"prompt_tokens":15,"prompt_time":0.002070754,"completion_tokens":204,"completion_time":0.328595312,"total_tokens":219,"total_time":0.330666066},"system_fingerprint":"fp_c5f20b5bb1","x_groq":{"id":"req_01jb7d7m3aet6bdgqqctm88txy"}}
```

Does this help us understand the problem?

**Comment by lmangani** [comment]
Not really, since you're receiving a 404 for the same destination, unless something is wrong with the parameter.
The only thing I'm thinking is you might have an older version of the extension loaded. To find out lets try this:

```
SELECT set_api_url('https://api.groq.com/openai/v1/chat/completions');
SELECT set_api_token('gsk_CIhrphxxxxxxxxxxxxxxxxxxxxxxxxxxjBXPEIRHuz');
SELECT set_model_name('groq-llama3-70b');
```

and then 

```
SELECT open_prompt('Write a one-line poem about ducks') AS response;
```

If any of the above works, it means the community extension repo is still serving an older release and we'll investigate.

**Comment by aborruso** [comment]
The conclusion is that I am really stupid: it works perfectly.
I got the model name wrong, so it didn't find it and I had 404. The correct name is `llama3-70b-8192`.

I take advantage of this for a question: how do I set them as default? Should I add them to the `.duckdbrc` file?

Thank you and sorry for the time I am wasting.

**Comment by lmangani** [comment]
Ciao @aborruso thanks for sharing an update! I really appreciate it. This is all new, so don't feel at fault. What we need to do is collect and document more working examples, and this definitely helps do that. 

In the next release we're going to add SECRETS which are persistent, right now you have to pass the parameters into the session manually or via SQL statements in your `.duckdbrc` if you're using the DuckDB CLI.
