### ISSUE TITLE
Running in Docker WSL:  Getting "Error: HTTP error 404: Not Found" Response

### ISSUE THREAD

**Issue by datamike** [quackscience/duckdb-extension-openprompt#13]
I did some searching about how to find the running models (`ollama list` in the Docker Desktop command line).  It showed that there were no models.

So I tried to find a not-so-large model (~1.3 GB) and ran `ollama pull llama3.2:1b`.  Then ran `ollama list` again to verify it was there.

Updated the openprompt_model_name variable with 'llama3.2:1b' and tried again with DuckDB query:  

`SELECT open_prompt('Write a one-line poem about ducks') AS response;`

:-)  

"With feathers bright as morning dew, they glide serene and slow, their quacks echoing soft as summer snow."

Thanks for creating this extension!

**Comment by lmangani** [comment]
I'm not sure if this is an issue or not, since the output seems to suggest it works :) Closing for now but feel free to reopen anytime if you have an issue. Happy holidays!
