### ISSUE TITLE
SET VARIABLE openprompt_api_timeout

### ISSUE THREAD

**Issue by caobingsheng** [quackscience/duckdb-extension-openprompt#14]
I believe we should add an environment variable to set the timeout, as 10 seconds is sometimes not enough.

**Comment by lmangani** [comment]
Hey @caobingsheng [this](https://github.com/quackscience/duckdb-extension-openprompt/pull/15) should do it but its untested.
Are you able to build and test the branch locally by any chance? If not I'll do it once time allows.

**Comment by lmangani** [comment]
Implemented in the latest release
