### ISSUE TITLE
Is there support for HTTPS for chat/completions API

### ISSUE THREAD

**Issue by skandaramesh** [quackscience/duckdb-extension-openprompt#17]
When using APIs that requires SSL getting the following error.

[
    {
        "error": {
            "code": 403,
            "message": "SSL is required to perform this operation.",
            "status": "PERMISSION_DENIED"
        }
    }
]

**Comment by lmangani** [comment]
@skandaramesh i ported some changes from http_client which should fix the issue in the latest release. We just published it today so it might take a second to update and/or require FORCE INSTALL. Let us know if it works as intended!
