### ISSUE TITLE
Not able to install

### ISSUE THREAD

**Issue by aborruso** [quackscience/duckdb-extension-openprompt#9]
Hi to all and thank you for this extension.

If I run `INSTALL open_prompt FROM community` I get

```
HTTP Error: Failed to download extension "open_prompt" at URL "http://community-extensions.duckdb.org/v1.1.0/linux_amd64_gcc4/open_prompt.duckdb_extension.gz" (HTTP 403)
```

Am I doind something wrong?

Thank you

**Comment by lmangani** [comment]
This extension is only available for the latest version of DuckDB. 
Upgrading your DuckDB to v1.1.2 will make the extension work 👍 
Thanks for giving this a try @aborruso

**Comment by aborruso** [comment]
I'm stupid, thank you

**Comment by lmangani** [comment]
> I'm stupid, thank you

Not at all. The Community Extensions repo is still new and many things are still in process. Thanks for reporting this!
